//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_app_with_file_upload.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Employee
    {
        public int Id { get; set; }

        [Required(ErrorMessage ="Please provide a valid employee name")]
        [DisplayName("Employee Name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please provide a valid employee designation")]
        public string Designation { get; set; }

        [DisplayName("Employee Image")]
        public string Img_path { get; set; }

        [Required(ErrorMessage = "Please provide a valid employee image")]
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
